---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AcmCertificate:
    Type: 'String'
    Description: |
      ARN of ACM certificate to serve contents via HTTPS.
  HostedZone:
    Type: 'AWS::Route53::HostedZone::Id'
    Description: |
      Route53 Hosted Zone where ALIAS records should be created.
  SiteHostname:
    Type: 'String'
    Description: |
      Hostname under which static site will be served.
  ApiGatewayEndpoint:
    Type: 'String'
    Description: |
      Endpoint of API Gateway.

Resources:
  StaticSite:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'static-site.yml'
      Parameters:
        AcmCertificate: !Ref 'AcmCertificate'
        HostedZone: !Ref 'HostedZone'
        Hostname: !Ref 'SiteHostname'

  Lambda:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'lambda.yml'
      Parameters:
        ApiGatewayEndpoint: !Ref 'ApiGatewayEndpoint'
